// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_NewSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ActionMid
        {
            get
            {
                return SteamVR_Actions.newSet_ActionMid;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionForward
        {
            get
            {
                return SteamVR_Actions.newSet_ActionForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean NewAction
        {
            get
            {
                return SteamVR_Actions.newSet_NewAction;
            }
        }
    }
}
