// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_KngGuns1 : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single ShootGunSqueezAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_ShootGunSqueezAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ReloadGunAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_ReloadGunAction;
            }
        }
        
        public virtual SteamVR_Action_Single SwitchGunSwipeAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_SwitchGunSwipeAction;
            }
        }
        
        public virtual SteamVR_Action_Single SwitchScopeSwipeAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_SwitchScopeSwipeAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabReleaseGunAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_GrabReleaseGunAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShootGunClickAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_ShootGunClickAction;
            }
        }
        
        public virtual SteamVR_Action_Vector2 DpadAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_DpadAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapGunsClick
        {
            get
            {
                return SteamVR_Actions.kngGuns1_SwapGunsClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchedPadAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_TouchedPadAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextScopeAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_NextScopeAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrevScopeAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_PrevScopeAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextGunAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_NextGunAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrevGunAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_PrevGunAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopShootGunAction
        {
            get
            {
                return SteamVR_Actions.kngGuns1_StopShootGunAction;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptics
        {
            get
            {
                return SteamVR_Actions.kngGuns1_Haptics;
            }
        }
    }
}
