/**
 * Autogenerated by Thrift Compiler (Shiyao Modified base on 0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;
using Thrift.Proxy;

namespace BlueprintReality.MixCast.SharedTexture
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SharedTexPacket : TBase
  {

    public string Id { get; set; }

    public SharedTex Info { get; set; }

    public SharedTexPacket() {
    }

    public SharedTexPacket(string id, SharedTex info) : this() {
      this.Id = id;
      this.Info = info;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_id = false;
        bool isset_info = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Id = iprot.ReadString();
                isset_id = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                Info = new SharedTex();
                Info.Read(iprot);
                isset_info = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_id)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Id not set");
        if (!isset_info)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Info not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("SharedTexPacket");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Id == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Id not set");
        field.Name = "id";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Id);
        oprot.WriteFieldEnd();
        if (Info == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Info not set");
        field.Name = "info";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Info.Write(oprot);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("SharedTexPacket(");
      __sb.Append(", Id: ");
      __sb.Append(Id);
      __sb.Append(", Info: ");
      __sb.Append(Info== null ? "<null>" : Info.ToString());
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
